version: "3.8"
services:
  abm-shipment-quote-api:
    image: abm-shipment-quote-api
    container_name: abm-shipment-quote-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8532:8000"
    volumes:
      - .:/app
